spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${MYAPP_JDBC_URL}
    username: ${MYAPP_JDBC_USER}
    password: ${MYAPP_JDBC_PASS}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: update
cors:
  url: ${MYAPP_CORS_URL}

jwt:
  secret: "mother_of_all_omelettes"
  subject: "user_details"
  issuer: "Shop_Map_Web_App"
  expiration_period_minutes: 120